apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: loki
  namespace: argo
spec:
  destination:
    namespace: loki
    server: https://kubernetes.default.svc
  project: default
  source:
    path: loki
    repoURL: https://github.com/OndraK2/KubeExample.git
    targetRevision: HEAD
  syncPolicy:
    syncOptions:
    - CreateNamespace=true
